import { Inter } from 'next/font/google'
import './globals.css'
import CustomNavBar from './component/common/customHeader/page'
import CustomFooter from './component/common/customFooter/page'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Manipal Community',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} style={{display:'flex',flexDirection:'column',height:'100%',width:'100%'}}>
        <div className='h-[15%]'>
        <CustomNavBar/>
        </div>
        {children}
        <footer className='bottom-0 w-full min-w-[1330px]'>
        <CustomFooter/>
        </footer>
        </body>
    </html>
  )
}
